version: "3.8"
networks:
  react-project-network:
    driver: bridge
services:
  nginx:
    image: nginx:stable-alpine
    container_name: react_project_nginx
    ports:
      - "8005:80"
    volumes:
      - ./src:/var/www/
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
      - react-project-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_project_app
    volumes:
      - ./src:/var/www/
    ports:
      - "9001:9000"
    networks:
      - react-project-network

  db:
    image: mariadb:10.5.6
    container_name: react_project_db
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: react_project_db
      MYSQL_ROOT_PASSWORD: hossainrkbreactproject
      MYSQL_USER: reactprojectdb
      MYSQL_PASSWORD: brofest78668713
    volumes:
      - react_project_db:/var/lib/mysql
    networks:
      - react-project-network

  phpmyadmin:
    image: phpmyadmin
    container_name: react_project_phpmadmin
    restart: always
    ports:
      - 8083:80
    networks:
      - react-project-network
volumes:
  react_project_db:
